<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net6.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	<Nullable>enable</Nullable>
	<ApplicationIcon>Images\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Images\icon.ico" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="NAudio" Version="2.1.0" />
  </ItemGroup>

</Project>
